### ISSUE TITLE
Produced docm cannot be opened in MS Office 2013

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#1]
I produced a Word document from:

http://www.oxygenxml.com/forum/files/flowers.zip

The produced DOCM cannot be opened in MS Office 2013, it says:

We are sorry. We cannot open flowers.docm because we found a problem with its contents.
Details: 
Unspecified error
Location: Part: /word/document.xml Line 1, Column 0

**Comment by jelovirt** [comment]
Issue is with `glossentry`, the current stylesheet only support `glossentry` inside `glossgroup`. I think I'll need to add some preprocessing to group those together, so that the glossary output will be a single list (as opposed to separate topics).

**Comment by jelovirt** [comment]
As workaround, if you change the glossary `topichead` into `<topicref href="concepts/glossary.dita" navtitle="Glossary">` where the `glossary.dita` is a `glossgroup` topic with just the title, the output should be correct.

**Comment by raducoravu** [comment]
Thanks Jarno, I will try that.

**Comment by jelovirt** [comment]
Ungrouped glossary entries are now output in separate tables, but Word merges sibling tables.

**Comment by raducoravu** [comment]
Great, I confirm that the fix works.
One warning that all published and opened docm's gave when opened in MS Office was this one:

{quote}
This document contains fields which may refer to other files. Do you want to update the fields in this document?
{quote}

but after updating the fields the document was opened so this is not a blocker.

**Comment by jelovirt** [comment]
See [FAQ](https://github.com/jelovirt/com.elovirta.ooxml/wiki/FAQ)-
