### ISSUE TITLE
Plugin is not compatible with DITA OT 4.x

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#101]
See:
https://stackoverflow.com/questions/75073076/dita-ot-4-0-1-dota015ffatal-internal-property-preprocess-copy-html-skip-may

in the "dita-ot/plugins/com.elovirta.ooxml-master/build.xml" these property definitions:

    <property name="preprocess.copy-image.skip" value="true"/>
    <property name="preprocess.copy-html.skip" value="true"/>

should be replaced with:

    <property name="build-step.copy-image" value="false"/>
    <property name="build-step.copy-html" value="false"/>

**Comment by RoxanaCurticapean** [comment]
@raducoravu is there a way to install the plugin with these properties set in a docker image?

My Dockerfile looks like:
\# Use the latest DITA-OT image ↓ as parent:
FROM ghcr.io/dita-ot/dita-ot:4.0.2

\# Install from the registry at dita-ot.org/plugins:
RUN dita --install  com.elovirta.ooxml

**Comment by raducoravu** [comment]
@RoxanaCurticapean I have not tested but think that when running the "dita" executable you can add these params in the command line:

    dita -i ...   --build-step.copy-image=false  --build-step.copy-html=false

**Comment by jelovirt** [comment]
@raducoravu are you able to submit a PR because you've already done the work of finding where the fix should go?

**Comment by raducoravu** [comment]
@jelovirt ok, I created PR #103

**Comment by RoxanaCurticapean** [comment]
Hi @raducoravu @jelovirt 

Thanks for your quick fix!
Do you know when it will be released/ready to be used? 

Regards,
Roxana

**Comment by raducoravu** [comment]
@RoxanaCurticapean not sure when @jelovirt plans a release but the plugin can also be used as it is, just by downloading the zip with the latest plugin code and integrating the plugin folder in the DITA OT:
https://github.com/jelovirt/com.elovirta.ooxml/archive/refs/heads/develop.zip

**Comment by RoxanaCurticapean** [comment]
@raducoravu that's great!
Thanks!
