### ISSUE TITLE
DITA To Word | Topics are not rendered if <fn> element is added in topic content.

### ISSUE THREAD

**Issue by DeekshaBhagat** [jelovirt/com.elovirta.ooxml#105]
Topic having<fn> element is not rendered and ailing at merge stage,
I am using [com.elovirta.ooxml](https://github.com/jelovirt/com.elovirta.ooxml) plugin to convert a ditamap into word.

I am getting at docx.merge stage - 

_docx.merge:
 [pipeline] Processing file:/D:/work_dsi/PDFPublishThemeTest/logs/TestMap.ditamap
 [pipeline] file:/D:/work_dsi/PDFPublishThemeTest/content/TestMap.ditamap:7:39: [DOTX008E][ERROR] File 'file:/D:/work_dsi/PDFPublishThemeTest/logs/TestTopic.dita' does not exist or cannot be loaded.
 [pipeline] TopicMergeModule processing took 117 ms_

PFA contents - 
[DitaMapToWord.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/11817886/DitaMapToWord.zip)

**Comment by DeekshaBhagat** [comment]
I am working on windows and using below command to - 

_dita --input=D:\work_dsi\PDFPublishThemeTest\content\TestMap.ditamap --format=docx-3ds --output=D:\work_dsi\PDFPublishThemeTest\content\out --temp=D:\work_dsi\PDFPublishThemeTest\logs --clean.temp=no -d_

Also if I remove the fn element it works fine.
![image](https://github.com/jelovirt/com.elovirta.ooxml/assets/90253219/80ab695a-20d5-4624-969d-d30004870e48)

**Comment by raducoravu** [comment]
This problem is not related to the published format, your TestTopic.dita is invalid, you are not allowed to insert a footnote inside a bold element. The bold element allows only these sub elements: https://www.oxygenxml.com/dita/1.3/specs/contentmodels/cmltb.html#cmltb__b
So the DITA OT issues an error when processing the TestTopic.dita and then skips over it.

**Comment by DeekshaBhagat** [comment]
@raducoravu Thank you for your response.
Yes, it started working when I take footnotes out from <b> element.

There is a new finding. Sharing just for information -
A new DITA version has been launched "dita-ot-4.1" on 22 June 2023. We downloaded it and rendered a Word document.
This latest version, allows <b> element to contain footnotes.

Earlier versions don't allow the fn element inside the b element.

TestTopic.dita
![image](https://github.com/jelovirt/com.elovirta.ooxml/assets/90253219/1fa32e3c-2a90-45ec-bf79-b1554e8a9549)

**Comment by DeekshaBhagat** [comment]
We can close this issue. Thank you helping :)

**Comment by DeekshaBhagat** [comment]
Solved.
