### ISSUE TITLE
Parameter id is not declared in the called template

### ISSUE THREAD

**Issue by xephon2** [jelovirt/com.elovirta.ooxml#11]
Processing fails with message `Parameter id is not declared in the called template`.

The error points to the following template in 
`document.abbrev-d.xsl`

```xml
<xsl:template match="*" mode="ditamsg:no-glossentry-for-abbreviated-form">
  <xsl:param name="keys"/>
  <xsl:call-template name="output-message">
    <xsl:with-param name="id">DOTX060W</xsl:with-param>
    <xsl:with-param name="msgparams">%1=<xsl:value-of select="$keys"/></xsl:with-param>
  </xsl:call-template>
</xsl:template>
```

Stacktrace: [stacktrace.txt](https://github.com/jelovirt/com.elovirta.ooxml/files/261013/stacktrace.txt)

**Environment**
* dita-ot: `2.2.5`
* com.elovirta.ooxml: [9d2f637](https://github.com/jelovirt/com.elovirta.ooxml/commit/9d2f637abe55defa610bff284636f987fdf97b63)

**Comment by raducoravu** [comment]
It will probably work with a DITA OT 2.x built directly from the "develop" main branch. I saw Jarno added that extra parameter to the "output-message" template some time ago.

**Comment by xephon2** [comment]
Hi @raducoravu, thanks a lot. I'll try that.

**Comment by xephon2** [comment]
As @raducoravu suggested, it works with [dita-ot-develop](https://s3-eu-west-1.amazonaws.com/dita-ot/dita-ot-develop.zip). I'll close the issue.
