### ISSUE TITLE
Transform fails when transforming to docx

### ISSUE THREAD

**Issue by juliovaz** [jelovirt/com.elovirta.ooxml#12]
While transforming a document using the plugin, the build fails with the error shown in the attached log file.
[ant.log.txt](https://github.com/jelovirt/com.elovirta.ooxml/files/473296/ant.log.txt)

The document does build with a PDF-based transform and although the message appears to come from the simpletable template, there is no simpletable in the source. 

I've attached a zip file of the temp directory created by the transform.
[temp.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/473298/temp.zip)

**Comment by raducoravu** [comment]
Your log file seems to indicate that the transtype is "rtf". And also it is incomplete.

**Comment by juliovaz** [comment]
Must have included the wrong log file.

sent from Android

**Comment by juliovaz** [comment]
Here's the correct log file.
[ant.log.txt](https://github.com/jelovirt/com.elovirta.ooxml/files/474629/ant.log.txt)

**Comment by raducoravu** [comment]
Looks like you have a simple table with the @relcolwidth attribute set to "1.919in" for one of the columns. Not very common and not sure if the specification allows for it:
https://docs.oasis-open.org/dita/v1.2/os/spec/langref/simpletable.html

**Comment by juliovaz** [comment]
Understood. I'll pass it on to the person who is responsible for the
content.

sent from Android
