### ISSUE TITLE
Reported ambiguos rule match

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#2]
During the transformation an ambiguous rule match is reported:

     [xslt] : Error! Ambiguous rule match for /map/topic[4]/glossentry[1]/glossterm[1]
     [xslt] Matches both "*[contains(@class, ' glossentry/glossterm ')]" on line 654 of file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/com.elovirta.ooxml/docx/word/document.topic.xsl
     [xslt] and "*[contains(@class, ' topic/topic ')]/ *[contains(@class, ' topic/title ')]" on line 114 of file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/com.elovirta.ooxml/docx/word/document.topic.xsl

**Comment by jelovirt** [comment]
Fixed as part of #960da84.
