### ISSUE TITLE
DITA Title - Word Heading numbering doubled up

### ISSUE THREAD

**Issue by mhGLEIF** [jelovirt/com.elovirta.ooxml#24]
I'm getting the numbering from my Word styles (in the normal.dotm template) plus the additional title numbering I assume from the DITA processing for a total of 2 numbers per top level heading in the Word doc output. Is there any way to stop adding heading numbers into the heading text when the Word style is a numbered style (I guess probably not)?

**Comment by jelovirt** [comment]
Hard-coded heading numbers should be behind a switch, the default being do not generate numbers.

**Comment by jelovirt** [comment]
@mhGLEIF as a quick fix, override the `numbering` mode to generate nothing. If you're not familiar with XSLT coding, modify https://github.com/jelovirt/com.elovirta.ooxml/blob/master/docx/word/document.topic.xsl#L175,L194 to be just

```xml
 <xsl:template match="*[contains(@class, ' topic/topic ')]/
                        *[contains(@class, ' topic/title ')]"
mode="numbering"/>
```

**Comment by mhGLEIF** [comment]
HI @jelovirt, commenting out the `xsl:if` appears to work, great!
