### ISSUE TITLE
Word output not opening after adding XML (XSD) codeblock

### ISSUE THREAD

**Issue by mhGLEIF** [jelovirt/com.elovirta.ooxml#27]
I'm working on oxygen 18.1 and Word for Mac.

I created a dita book map, it output just fine as a Word doc, but after adding a reference topic that contains a codeblock presenting a valid XSD file, Word refuses to open the output file.

![image](https://cloud.githubusercontent.com/assets/15021888/24197948/0614f832-0f04-11e7-83d3-bcba04784d51.png)

**Comment by jelovirt** [comment]
This is a case where there's something in the generate OOXML file that not correct per the spec and Word is rejecting it. Unfortunately Word gives you very little or absolutely no debugging information.

If you can create a DITA source set that will reproduce this issue, please upload the ZIP here.

**Comment by jelovirt** [comment]
Note that Oxygen doesn't necessarily ship with the latest version of the OOXML plugin. Due to lack of resource, this issue tracker only handles bugs in the latest version.

**Comment by mhGLEIF** [comment]
Thank you! 😄 

Here's a zip with the XSD, the reference topic containing the XSD, and the DITA bookmap containing the ref topic... plus the .docm output (I couldn't open it sadly).


[Archive.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/861570/Archive.zip)

**Comment by mhGLEIF** [comment]
Not to worry, I will ask the oxygen team if it's easy enough to update the plugin (without losing my customizations!).

**Comment by raducoravu** [comment]
Oxygen team is listening in :)
Jarno's plugin is usually present in:

   OXYGEN_INSTALL_DIR\frameworks\dita\DITA-OT2.x\plugins\com.elovirta.ooxml

so you need to update it and possibly run the DITA OT integrator:

https://www.oxygenxml.com/doc/versions/18.1/ug-editor/topics/dita-ot-install-plugin.html

Oxygen 19 will come with the latest plugin fixes included.

**Comment by jelovirt** [comment]
Works with latest code
