### ISSUE TITLE
Multi-level lists

### ISSUE THREAD

**Issue by mhGLEIF** [jelovirt/com.elovirta.ooxml#28]
This is a kind of a subset of https://github.com/jelovirt/com.elovirta.ooxml/issues/26 but maybe there should be some logic involved too?

Multilevel lists (bullets and/or numbered) come up a lot in DITA and technical writing generally.

Would it make sense to have some logic to map the depth of the physical `<li>` tags in the DITA to the corresponding standard Word headings (`Bullet list` / `Numbered list`)?

**Comment by jelovirt** [comment]
Mapping different styles to different list item depths is something that you currently have to override. Again, since there is no single one answer for this, it's left to the customization to handle it.

**Comment by mhGLEIF** [comment]
I would suggest to standardize it to the built-in Word styles that appear in a fresh copy of `normal.dotm`:

![image](https://cloud.githubusercontent.com/assets/15021888/24394698/45595b58-139d-11e7-86f4-daa603180543.png)

Is this something the user community is expected to do?

I'm intending to learn XSLT in depth but I as far as I can understand these tweaks would not be a lot of work for someone who already knows - maybe oxygen can get it done somehow?

**Comment by jelovirt** [comment]
Sounds reasonable. I will implement this to be the default.

**Comment by mhGLEIF** [comment]
This is extremely helpful!

Sorry for the long exchange - sometimes even a technical writer is not able to explain their requirements as clearly as they'd like ;-)

**Comment by dagoss** [comment]
Would this be expected to affect `<task>` elements too, or are we just talking about basic list elements like `<ol>` and `<ul>`?

For example:

```xml
<steps>
    <step>
        <cmd>This is "List Number"</cmd>
        <info>This is "List Continue"</info>
    </step>
    <step>
        <cmd>This is "List Number"</cmd>
        <substeps>
            <substep>
                <cmd>This is "List Number 2"</cmd>
                <info>This is "List Continue 2"</cmd>
             </substep>
        </substep>
    </step>
    <step>
        <cmd>This is "List Number"</cmd>
        <choices>
            <choice>This is "List Bullet 2"</choice>
        </choice>
    </step>
</steps>
```

**Comment by mhGLEIF** [comment]
@dagoss I was assuming just `ol` and `ul` because they are semantic-free and could therefore reasonably be expected to behave like Word styles (which are _almost_ all semantic free).

There's no Word style that corresponds to most of the DITA semantic elements.

`codeph` might work as e.g. `HTML Code` (which I'd suggest) but I will admit I don't know what all the other Word `HTML _____` styles mean.
