### ISSUE TITLE
xref keyref not properly resolved

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#3]
In this sample:

http://www.oxygenxml.com/forum/files/flowers.zip

the lilac.dita has an xref like this:

     <xref keyref="flowers.genus" format="dita">genus</xref>

but the generated word document contains something like:

     Lilac (Syringa) is a Error! Reference source not found.

**Comment by jelovirt** [comment]
Exactly which topic? The `<xref>` elements I'm look at seem to work with the latest code.

Note here that Word has an interesting feature here. It will always pull the cross-reference text from the target bookmark and I haven't found a way to override that. Thus, in the `flowers.genus` definition reference, the cross-reference text will be "Genus" from the glossary entry, not the inline "genus" text.

**Comment by raducoravu** [comment]
It works after your latest changes so I will close this one. Originally I did not update on my side the entire XSLT stylesheet.
