### ISSUE TITLE
Build error in docx.image-metadata

### ISSUE THREAD

**Issue by ToshihikoMakita** [jelovirt/com.elovirta.ooxml#34]
I encountered build error in docx.image-metadata when I installed this plug-in into DITA-OT 2.4.6.

```
preprocess:

docx.image-metadata:

BUILD FAILED
D:\DITA-OT\dita-ot-2.4.6\build.xml:45: The following error occurred while executing this line:
D:\DITA-OT\dita-ot-2.4.6\plugins\com.elovirta.ooxml\build.xml:36: module doesn't support the nested "ditaFileset" element.

Total time: 13 seconds

The process finished with exit code: 1
```
I attached sample data and log file. Could you suggest me how to solve this issue?

[20170419-sample-en-for-word.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/1022217/20170419-sample-en-for-word.zip)

Regards,

Toshihiko Makita

**Comment by jelovirt** [comment]
Did you use code from `master` or from [release 1.2](https://github.com/jelovirt/com.elovirta.ooxml/releases/tag/1.2.0). Code from `master` unfortunately relies on DITA-OT 2.5 features, this is a mistake I made in pushing to `master` instead of `develop`.

**Comment by ToshihikoMakita** [comment]
Thank you!
I understand the situation.
For my testing, I will use the plug-in bundled in oXygen 19.0.
I've confirmed that works fine without build errors.

Regards,
