### ISSUE TITLE
Redundant w:num & w:abstractNum in numbering.xml

### ISSUE THREAD

**Issue by ToshihikoMakita** [jelovirt/com.elovirta.ooxml#36]
.docx/word/numbering.xml contains:

1. Redundant w:abstractNum. It is generated per list. In practical it should be defined once and should be reused via w:num. 
2. Non referenced w:num(s). They are not used from word/document.xml.

[20170524-list.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/1025792/20170524-list.zip)

This sample is generated via oXygen 19.0 bundled plug-in.

**Comment by jelovirt** [comment]
This is something I'm not going to change right now. If you mix `<ol>` and `<ul>` at different levels, they all need different abstract numbering configuration. The code could try to combine them into one, but for now it's just easier to generate one for each list.

The unused `w:num` probably come from template.
