### ISSUE TITLE
Update ant-contrib

### ISSUE THREAD

**Issue by xephon2** [jelovirt/com.elovirta.ooxml#42]
The ant-contrib library is outdated. The shipped version is **0.6** (from 2004-02-18). The current version **1.0b3** is a little bit newer (2006-11-02). This is a library that is usually shipped by many DITA-OT plugins. Therefore you might get into trouble when importing it multiple times in different versions.

- It would be nice, if the library would be updated.
- To externalize it, you can also use the utility plugin [org.doctales.ant-contrib](https://github.com/doctales/org.doctales.ant-contrib). I usually add an addtional checker step that looks at the classpath for **ant-contrib** and fail, if it isn't available. Setting **org.doctales.ant-contrib** as a requirement could also work but may lead to issues, if a user does not want to install it, because another plugin already provides that library.

But maybe **ant-contrib** is completely obsolete here, as stated in https://github.com/jelovirt/com.elovirta.ooxml/issues/40#issuecomment-310351660

**Comment by raducoravu** [comment]
Probably a duplicate of #23

**Comment by xephon2** [comment]
Sorry @raducoravu, I did not see this one.

**Comment by jelovirt** [comment]
The problem with ant-contrib is that it's basically abandonware.

**Comment by xephon2** [comment]
Do you know a replacement for it, as it ships in fact core functionality, that are mandatory to use Ant efficiently?
