### ISSUE TITLE
Possible cell span bug in table header

### ISSUE THREAD

**Issue by ToshihikoMakita** [jelovirt/com.elovirta.ooxml#48]
I found possible cell span bug in table header.

![span-bug](https://user-images.githubusercontent.com/1801890/34455123-92d3ae6c-edbb-11e7-9987-2dfe532e28f5.png)

This should be converted as follows:

![span-fixed](https://user-images.githubusercontent.com/1801890/34455151-19b1f7ae-edbc-11e7-9536-62e37a91bc3a.png)

I attached the sample DITA instance and sample result.

[mTableCellSpanningTest.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/1594472/mTableCellSpanningTest.zip)

[mTableCellSpanningTest-ooxml.docx](https://github.com/jelovirt/com.elovirta.ooxml/files/1594475/mTableCellSpanningTest-ooxml.docx)

[mTableCellSpanningTest-ah-wml.docx](https://github.com/jelovirt/com.elovirta.ooxml/files/1594478/mTableCellSpanningTest-ah-wml.docx)

**Comment by c-alpha** [comment]
Hello @ToshihikoMakita. It seems I just ran into the same or a similar issue. Cell spanning works fine in the table body, but not in the header.

Did you find any solution in the end?

**Comment by ToshihikoMakita** [comment]
Hi @c-alpha,
I detected this bug when I was developing own DITA to .docx plug-in in year 2017. So my plug-in  generates .docx file correctly. If you have any interest in DITA to .docx conversion, please visit my repository.
[https://github.com/AntennaHouse/ah-wml](https://github.com/AntennaHouse/ah-wml)

**Comment by c-alpha** [comment]
It seems this has been fixed with [dita-ot 3.5.2](https://github.com/dita-ot/dita-ot/compare/3.5.1...3.5.2).

**Comment by ToshihikoMakita** [comment]
Fix confirmed using the newest master branch.

![fix-2020-08-05](https://user-images.githubusercontent.com/1801890/89357936-dd3bae00-d6fc-11ea-8ef0-0b609cb15cbf.png)
