### ISSUE TITLE
Invalid OOXML output when publishing DITA 1.3 Specs

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#5]
I downloaded the DITA 1.3 specs from SVN and published the DITA Map "dita-1.3-specification-learningTraining.ditamap" to OOXML.
The resulting ooxml file is invalid.
Reported error when it is opened in MS Office 2013:

      Ambiguous cell mapping encountered. Possible missing paragraph element. <p> elements are required before every </tc>.
     Location: Part: /word/document.xml, Line 78, Column 0

**Comment by jelovirt** [comment]
#cc725cb fixes footnote references and the DITA 1.3 spec now opens without errors.

**Comment by raducoravu** [comment]
Great, I tested it and the produced manual could be opened successfully.

**Comment by jelovirt** [comment]
Cross-references are still broken, but those will be fixed in a separate issue.
