### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by chrizzbee** [jelovirt/com.elovirta.ooxml#54]
When a colleague of mine runs the OOXML transformation on her PC, she gets the following strange timezone error: 

[xslt] D:\$_checkout\$_docs\oxygenDocs\trunk\_oxygen\_ditaOT2.x\plugins\com.elovirta.ooxml\docx\word\document.utils.xsl:42: Fatal Error! Invalid dateTime value "2017-08-31T16:37:26+0200" (Timezone hour must be two digits)
     [xslt] Failed to process C:\Users\xxx.xxx\oxygenOut\temp\oxygen_dita_temp\mcad_installAdminGuide-en_CLEANED.xml

BUILD FAILED
D:\$_checkout\$_docs\oxygenDocs\trunk\_oxygen\_ditaOT2.x\build.xml:45: The following error occurred while executing this line:
D:\$_checkout\$_docs\oxygenDocs\trunk\_oxygen\_ditaOT2.x\plugins\com.elovirta.ooxml\build.xml:112: Fatal error during transformation using D:\$_checkout\$_docs\oxygenDocs\trunk\_oxygen\_ditaOT2.x\plugins\com.elovirta.ooxml\docx\word\comments.xsl: Invalid dateTime value "2017-08-31T16:37:26+0200" (Timezone hour must be two digits); SystemID: file:/D:/$_checkout/$_docs/oxygenDocs/trunk/_oxygen/_ditaOT2.x/plugins/com.elovirta.ooxml/docx/word/document.utils.xsl; Line#: 42; Column#: -1

It works on my machine though. As far as I can tell, she and I have the same time settings.

**Comment by raducoravu** [comment]
Looks like a duplicat of https://github.com/jelovirt/com.elovirta.ooxml/issues/43
