### ISSUE TITLE
How to use custom templates?

### ISSUE THREAD

**Issue by CharmingLee** [jelovirt/com.elovirta.ooxml#56]
I use my templates convert dita file to word ，the result has no effect.But I use the default template "resources/Normal.docx" conversion result is normal.I tried to modify the style on the default template, but the result is nothing and even the default style is not.I can confirm that there is no error in the ditaOT.

**Comment by jelovirt** [comment]
The only current documentation is at https://github.com/jelovirt/com.elovirta.ooxml/wiki/Templates
