### ISSUE TITLE
Want to display landscape pages in word output.

### ISSUE THREAD

**Issue by rahulraykor** [jelovirt/com.elovirta.ooxml#59]
I need to display some topics on landscape pages in word, depending on some custom properties set in topic XML.
As far as I know that support was there in DITA Exchange conversion.
How can I do this?

Below is the property I want to use for Landscape view.

<topic id='Table'  ditaarch:DITAArchVersion='1.2' domains='(topic ui-d)(topic hi-d)(topic sw-d)(topic pr-d)(topic ut-d)(topic indexing-d)' class='- topic/topic ' xmlns:ditaarch='http://dita.oasis-open.org/architecture/2005/' 
 **outputclass='Dx:Landscape'** >

**Comment by rahulraykor** [comment]
Can we do it by referencing [org.doctales.custom-pdf](https://github.com/doctales/org.doctales.custom-pdf) this plugin?

**Comment by raducoravu** [comment]
That particular plugin is for PDF output and not for Word output.

**Comment by rahulraykor** [comment]
This plugin will not work for a map. If we have a map then after "transform.fo2pdf.fop" we only have "ditamap-body-sequnce" in the generated FO file.

We can achieve this only if we manage to have multiple page sequence strategy in single FO file.
Like for output class landscpae we can set page sequence strategy to "landscape-sequence" and for other, we can have "body-sequence"

But how we can achieve this?
Do we need to generate separate FO files instead of a merged FO file and then combine all of them?
