### ISSUE TITLE
Table header doesn't stand out (bold and/or centered)

### ISSUE THREAD

**Issue by adriankarp** [jelovirt/com.elovirta.ooxml#77]
Hello!

Is there possible to make the table header different than the table body?
As far as I can see, right now, both of them apply the normal style.

Thank you
Kind regards
Adrian

**Comment by jelovirt** [comment]
@adriankarp Did you manage to solve this yourself?

**Comment by adriankarp** [comment]
@jelovirt  Yes, I managed to solve this.

I am trying to modify also other things. If you sometimes have spare time and wish to give me some tips, let me know!
