### ISSUE TITLE
Table of Contents page numbering

### ISSUE THREAD

**Issue by adriankarp** [jelovirt/com.elovirta.ooxml#79]
Hello!

The table of contents does not show the page numbers and the ordering position.
Is there a way to solve this problem?

Thank you!

Actual output:
  Example1 .......... 0
  Example2 .......... 0
     Example3 ...... 0

Desired output:
1  Example1 ........ 2
2  Example2 ........ 4
2.2  Example3 .... 5

**Comment by jonathanhanna** [comment]
When you first open the Word file after generating it, you will get a notification that says:

> This document contains fields that may refer to other files. Do you want to update the fields in this document?

If you click **No** (the default option), the table of contents will show all of the page numbers as 0. You must click **Yes** in order to get the page numbers to appear correctly.

**Comment by adriankarp** [comment]
Thank you very much for explaining!
