### ISSUE TITLE
bold <cmd> tag in task topic

### ISSUE THREAD

**Issue by adriankarp** [jelovirt/com.elovirta.ooxml#86]
Hello,

I am trying to make cmd's text bold. So far I managed to modify the number associated with the step, but no success in modifying the text.

![image](https://user-images.githubusercontent.com/28531641/121652938-d90eb880-caa4-11eb-98cc-5ed0b7e9741d.png)

How can I target the text inside the rectangle?

![image](https://user-images.githubusercontent.com/28531641/121653112-03607600-caa5-11eb-8f5a-88ec729f186e.png)

This is how I tried to modify cmd.
Can't seem to figure out how to insert bold inside that "p" template.

Thank you!

**Comment by jonathanhanna** [comment]
Assuming that you just want to make the `<cmd>` text bold, you can do this:
```
  <xsl:template match="*[contains(@class, ' task/cmd ')]" mode="inline-style">
    <w:b w:val="true"/>
  </xsl:template>
```

**Comment by adriankarp** [comment]
This solved my problem.
Thank you!
