### ISSUE TITLE
Internal cross- ref links is not working in your updated docx plugin

### ISSUE THREAD

**Issue by rag-sing** [jelovirt/com.elovirta.ooxml#92]

**Comment by raducoravu** [comment]
@rag-sing there is nothing specified on this issue, I see you asked on the DITA Users List about this. Maybe you can close this issue for now or provide details.

**Comment by rag-sing** [comment]
Hi all,

I am using base com.elovirta.ooxml plugin for generating docx output but I got issue in cross link if scope="peer" is present in our dita map. While it is working fine for all ditmap in which scope="local" or scope is not present in our ditamap.
For example in our Dita map:

<row rowsep="1">
        <entry align="left"><pwc-xref
          href="01_scope_and_the_red/11_the_uk_gaap_frame/summary_of_framework.UK.dita#pwc-topic.dita_1510041002153840/moa_new_ukgaap_1_1_5"
          format="dita" scope="peer">1.1.9<related-content value="yes"/></pwc-xref></entry>
        <entry align="left">Applicability of EU-adopted IFRS.</entry>
        <entry align="left"><pwc-xref
          href="1621243610153904.UK.dita#pwc-topic.dita_1621243610153904/moa_1_13_19" format="dita"
          scope="peer">UK.1.13.19 to UK.1.13.34<related-content value="yes"/></pwc-xref></entry>
       </row>
Note: you can use any ditamap just modify your scope="peer" then your base plugin is not working.
I tried to custmoze in document.link.xsl file still i am facing the same issue.

Could any one help me?

Thanks in advance!!!

Regards
Raghavednra

**Comment by rag-sing** [comment]
Hi all, 

I tried below point as Radu suggested me but my problem is not resolved ( if scope="peer" is present in our dita map then it is not working). While it is working fine for all ditmap in which scope="local" or scope is not present in our ditamap.)

1) We search scope=peer in pre-process plugin "DITA-OT/plugins/org.dita.base/",  and remove it in all 17 places. But it did not work.
2)  We search scope=peer in pre-process plugin "DITA-OT/plugins/org.dita.base/",  and replaces with scope=local.
3) At the time of above both steps we keep below  changed in document.link.xsl" .

<xsl:function name="x:get-target" as="element()?">
    <xsl:param name="link" as="element()?"/>

    <xsl:variable name="scope"
      select="
      if ($link/@scope and not($link/@scope='peer')) then

          $link/@scope
        else
          'local'"
      as="xs:string"/>


Could anyone give me other suggestion?
